### ISSUE TITLE
PHPConsole stopped working / no icon

### ISSUE THREAD

**Issue by nhorvath** [barbushin/php-console#85]
PHPConsole was working for me fine for a long time but today the icon will not show and no debug logs are displaying in the console. This is effecting all developers on this product across multiple branches so while it is possible it is environmental it is not likely caused by a code change. I've tested personally on Windows 7 and Ubuntu 14.04.2 and others have reported on OSX as well.

PHPConsole response headers look like this, but I'm not sure what successful ones are supposed to look like for comparison.
PHP-Console:{"protocol":5,"auth":{"publicKey":"HEX STRING REMOVED","isSuccess":false},"docRoot":null,"sourcesBasePath":null,"getBackData":null,"isLocal":null,"isSslOnlyMode":false,"isEvalEnabled":null,"messages":[]}
PHP-Console-Postpone:{"protocol":5,"isPostponed":true,"id":"169481652010446978121381394038"}

**Comment by nhorvath** [comment]
The console works still on your demo page so it's not like the extension is broken. Just looking for some guidance on what might be going wrong.

**Comment by barbushin** [comment]
Hey. Could you please send the link on web-page that PHP Console not works? And check if extension version you're using is >= `3.0.29`. Thank you.

**Comment by nhorvath** [comment]
Unfortunately I can't because our dev/qa is firewalled off and phpconsole only works when already logged in in production and I can't give out production logins for our clients.
I am using extension version 3.0.29

**Comment by barbushin** [comment]
What is domain name? Is it first level domain like `example.com` or with sub-domain `sub.example.com`?

**Comment by nhorvath** [comment]
they are all subdomains. in dev they are like clientid.branch.username.developers.mycompany.com and in production they are a first level subdomain of the client's domain.

**Comment by barbushin** [comment]
Ok, wait 10-30 min. I'll fix it.

**Comment by nhorvath** [comment]
Oh wow ok thanks! So I guess it was a change to the extension recently that broke it?

**Comment by andrewcroce** [comment]
I can confirm this. Sometime in the last hour or two PHP Console ceased to function. Unfortunately the code I am working on is only in my local environment. Maybe a Chrome update?

**Comment by barbushin** [comment]
Yes, it was :(

**Comment by barbushin** [comment]
Ok, guys, I published version `3.0.30`. Try to reinstall extension.

**Comment by andrewcroce** [comment]
Brilliant, that seems to have done the trick. Thanks for the super-quick response!

**Comment by nhorvath** [comment]
Yes that worked for me too. Thanks for the quick turnaround!

**Comment by amenadiel** [comment]
:+1: thanks for the swift response!

**Comment by hawkeye64** [comment]
Mine quit working at the same time, and I have upgraded to 3.0.30 and it's still not working for me. Any suggestions? My Chrome version is Version 43.0.2357.130 m.

**Comment by barbushin** [comment]
Hi. Try update to 3.0.33
09 июля 2015 г. 19:49 пользователь "Jeff Galbraith" <
notifications@github.com> написал:
